In [1]:
# importing packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#loading data
input_data_path = "car_price_problem5.csv"
data_df=pd.read_csv(input_data_path)
print(data_df.shape)
data_df.head()

(2059, 20)


Make                            Model    Price  Year  Kilometer  \
0          Honda              Amaze 1.2 VX i-VTEC   505000  2017      87150   
1  Maruti Suzuki                  Swift DZire VDI   450000  2014      75000   
2        Hyundai             i10 Magna 1.2 Kappa2   220000  2011      67000   
3         Toyota                         Glanza G   799000  2019      37500   
4         Toyota  Innova 2.4 VX 7 STR [2016-2020]  1950000  2018      69000   

  Fuel_Type Transmission   Location   Color   Owner Seller_Type   Engine  \
0    Petrol       Manual       Pune    Grey   First   Corporate  1198 cc   
1    Diesel       Manual   Ludhiana   White  Second  Individual  1248 cc   
2    Petrol       Manual    Lucknow  Maroon   First  Individual  1197 cc   
3    Petrol       Manual  Mangalore     Red   First  Individual  1197 cc   
4    Diesel       Manual     Mumbai    Grey   First  Individual  2393 cc   

            Max_Power              Max_Torque Drivetrain  Length   Width  \
0   87 bhp @ 6000 rpm       109 Nm @ 4500 rpm        FWD  3990.0  1680.0   
1   74 bhp @ 4000 rpm       190 Nm @ 2000 rpm        FWD  3995.0  1695.0   
2   79 bhp @ 6000 rpm  112.7619 Nm @ 4000 rpm        FWD  3585.0  1595.0   
3   82 bhp @ 6000 rpm       113 Nm @ 4200 rpm        FWD  3995.0  1745.0   
4  148 bhp @ 3400 rpm       343 Nm @ 1400 rpm        RWD  4735.0  1830.0   

   Height  Seating_Capacity  Fuel_Tank_Capacity  
0  1505.0               5.0                35.0  
1  1555.0               5.0                42.0  
2  1550.0               5.0                35.0  
3  1510.0               5.0                37.0  
4  1795.0               7.0                55.0

In [3]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2059 entries, 0 to 2058
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Make                2059 non-null   object 
 1   Model               2059 non-null   object 
 2   Price               2059 non-null   int64  
 3   Year                2059 non-null   int64  
 4   Kilometer           2059 non-null   int64  
 5   Fuel_Type           2059 non-null   object 
 6   Transmission        2059 non-null   object 
 7   Location            2059 non-null   object 
 8   Color               2059 non-null   object 
 9   Owner               2059 non-null   object 
 10  Seller_Type         2059 non-null   object 
 11  Engine              1979 non-null   object 
 12  Max_Power           1979 non-null   object 
 13  Max_Torque          1979 non-null   object 
 14  Drivetrain          1923 non-null   object 
 15  Length              1995 non-null   float64
 16  Width 

In [4]:
data_df.describe()

Price         Year     Kilometer       Length        Width  \
count  2.059000e+03  2059.000000  2.059000e+03  1995.000000  1995.000000   
mean   1.702992e+06  2016.425449  5.422471e+04  4280.860652  1767.991980   
std    2.419881e+06     3.363564  5.736172e+04   442.458507   135.265825   
min    4.900000e+04  1988.000000  0.000000e+00  3099.000000  1475.000000   
25%    4.849990e+05  2014.000000  2.900000e+04  3985.000000  1695.000000   
50%    8.250000e+05  2017.000000  5.000000e+04  4370.000000  1770.000000   
75%    1.925000e+06  2019.000000  7.200000e+04  4629.000000  1831.500000   
max    3.500000e+07  2022.000000  2.000000e+06  5569.000000  2220.000000   

            Height  Seating_Capacity  Fuel_Tank_Capacity  
count  1995.000000       1995.000000         1946.000000  
mean   1591.735338          5.306266           52.002210  
std     136.073956          0.822170           15.110198  
min    1165.000000          2.000000           15.000000  
25%    1485.000000          5.000000           41.250000  
50%    1545.000000          5.000000           50.000000  
75%    1675.000000          5.000000           60.000000  
max    1995.000000          8.000000          105.000000

In [5]:
data_df.isnull().sum(axis=0).sort_values(ascending=False)

Drivetrain            136
Fuel_Tank_Capacity    113
Max_Torque             80
Max_Power              80
Engine                 80
Seating_Capacity       64
Height                 64
Width                  64
Length                 64
Model                   0
Make                    0
Owner                   0
Color                   0
Location                0
Transmission            0
Fuel_Type               0
Kilometer               0
Year                    0
Price                   0
Seller_Type             0
dtype: int64

In [6]:
#dropping null values rows
data_df = data_df.dropna()
print(data_df.shape)
data_df.isnull().sum()

(1874, 20)


Make                  0
Model                 0
Price                 0
Year                  0
Kilometer             0
Fuel_Type             0
Transmission          0
Location              0
Color                 0
Owner                 0
Seller_Type           0
Engine                0
Max_Power             0
Max_Torque            0
Drivetrain            0
Length                0
Width                 0
Height                0
Seating_Capacity      0
Fuel_Tank_Capacity    0
dtype: int64

In [7]:
#target_df = df[["Price"]]
#print(target_df.shape)
#target_df.head()

In [8]:
#type(target_df)

In [9]:
#selecting subset of the dataset
subset_df = data_df[["Price","Year","Kilometer","Length","Width","Height","Seating_Capacity","Fuel_Tank_Capacity"]]
print(subset_df.shape)
subset_df.head()

(1874, 8)


Price  Year  Kilometer  Length   Width  Height  Seating_Capacity  \
0   505000  2017      87150  3990.0  1680.0  1505.0               5.0   
1   450000  2014      75000  3995.0  1695.0  1555.0               5.0   
2   220000  2011      67000  3585.0  1595.0  1550.0               5.0   
3   799000  2019      37500  3995.0  1745.0  1510.0               5.0   
4  1950000  2018      69000  4735.0  1830.0  1795.0               7.0   

   Fuel_Tank_Capacity  
0                35.0  
1                42.0  
2                35.0  
3                37.0  
4                55.0

In [10]:
# implementing onhot vector from sklearn
from sklearn.preprocessing import OneHotEncoder
ohe= OneHotEncoder()
onehot_data=ohe.fit_transform(data_df[['Make','Model','Fuel_Type','Transmission','Location','Color','Owner','Seller_Type','Engine','Max_Power','Max_Torque','Drivetrain']]).toarray()
print(onehot_data.shape)
onehot_data

(1874, 1774)


array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 1.]])

In [11]:
#extracting trager label
target = subset_df[["Price"]].to_numpy()
print(target.shape)
target

(1874, 1)


array([[ 505000],
       [ 450000],
       [ 220000],
       ...,
       [ 275000],
       [ 240000],
       [4290000]], dtype=int64)

In [12]:
#droping traget from input subset
subset = subset_df.drop(columns = ["Price"]).to_numpy()
subset.shape
subset

array([[2.0170e+03, 8.7150e+04, 3.9900e+03, ..., 1.5050e+03, 5.0000e+00,
        3.5000e+01],
       [2.0140e+03, 7.5000e+04, 3.9950e+03, ..., 1.5550e+03, 5.0000e+00,
        4.2000e+01],
       [2.0110e+03, 6.7000e+04, 3.5850e+03, ..., 1.5500e+03, 5.0000e+00,
        3.5000e+01],
       ...,
       [2.0140e+03, 8.3000e+04, 3.4950e+03, ..., 1.5000e+03, 5.0000e+00,
        3.2000e+01],
       [2.0130e+03, 7.3000e+04, 3.7950e+03, ..., 1.4270e+03, 5.0000e+00,
        4.5000e+01],
       [2.0180e+03, 6.0474e+04, 4.9360e+03, ..., 1.4790e+03, 5.0000e+00,
        6.5000e+01]])

In [13]:
complete_input = np.concatenate((subset, onehot_data), axis=1)
print(complete_input.shape)
complete_input


# input_df1=pd.concat([subset_df,input_df],axis=1)
# input_df1

(1874, 1781)


array([[2.0170e+03, 8.7150e+04, 3.9900e+03, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [2.0140e+03, 7.5000e+04, 3.9950e+03, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [2.0110e+03, 6.7000e+04, 3.5850e+03, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       ...,
       [2.0140e+03, 8.3000e+04, 3.4950e+03, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [2.0130e+03, 7.3000e+04, 3.7950e+03, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [2.0180e+03, 6.0474e+04, 4.9360e+03, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00]])

In [14]:
#input_df1=df1.drop(columns=['Make','Model','Price','Fuel_Type','Transmission','Location','Color','Owner','Seller_Type','Engine','Max_Power','Max_Torque','Drivetrain'])
#input_df1

In [15]:
# input_df1 = input_df1.dropna()
# input_df1.shape

In [16]:
# target_df = input_df1[["Price"]]
# print(target_df.shape)
# target_df.head()

In [17]:
# input_df2= input_df1.drop('Price', axis=1)
# print(input_df2.shape)
# input_df2.head()

In [18]:
# input_df=pd.DataFrame(input_df2)
# input_num= input_df.to_numpy()
# print(input_num.shape)
# print(target_df.shape)



In [19]:
#def absolute_maximum_scale(series):
    #return series / series.abs().max()

#for col in target_df.columns:
    #target_df[col] = absolute_maximum_scale(target_df[col])
#print(target_df) 

In [20]:
#def absolute_maximum_scale(series):
    #return series / series.abs().max()

#for col in input_df.columns:
    #input_df[col] = absolute_maximum_scale(input_df[col])
#print(input_df) 

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(complete_input, target, test_size=0.2, random_state=42, shuffle=True)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
y_train

(1499, 1781) (375, 1781) (1499, 1) (375, 1)


array([[ 145000],
       [ 299000],
       [3300000],
       ...,
       [ 795000],
       [1063000],
       [1300000]], dtype=int64)

In [22]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X_train.astype(float) , y_train.astype(float) )
print(reg.coef_)
print(reg.intercept_)
pred = reg.predict( X_test)

[[ 1.75768338e+05 -9.67559024e-01  5.88923112e+04 ...  9.88123101e+05
   4.49404974e+06 -5.48217285e+06]]
[-5.92704336e+08]


In [23]:
from sklearn.metrics import r2_score
score = r2_score( y_test, pred)
print("The accuracy of our model is {}%".format(round(score, 2) *100))

The accuracy of our model is -202.99999999999997%
